web:
  host: 0.0.0.0
  port: 8080

server:
  # 如果你想显示你的服务器连接信息的话，就把下面这个show-info改为true，否则保持不动
  show-info: true
  # 服务器名字
  name: 峰间云海
  # 外部连接地址
  external-host: mc.hzchu.top
  host: 192.168.1.58
  # 这个port只是拿来展示的，如果上面关掉了的话可以不动它
  port: 26565
  # 查询信息实际用的是query这个端口，在server.properties里面有，需要自行设置端口并且把这个功能打开
  query: 26566
  # 自定义服务器motd
  motd: "Welcome to the FClouds Server!"
  # 自定义页面icon
  favicon: /assets/favicon.ico
  logo: https://onep.hzchu.top/mount/pic/myself/2024/07/66946d9fd0cbf.jpg?fmt=webp
  preview:  # 服务器预览部分
    title: 嘿！这里是峰间云海
    # 预览界面的描述，可以用html书写
    descr: |
      峰间云海是一个生电服务器，里面有形形色色的玩家们。<br><a href="https://mcmap.hzchu.top:60181/" target="_blank"><u>查看在线地图</u></a>
      一周目宣传片：<br>
      <iframe src="//player.bilibili.com/player.html?isOutside=true&aid=316642962&bvid=BV1BP41167UW&cid=1218587437&p=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>
    images: # 服务器的预览图片，你需要把文件丢在images文件夹里面，然后复制文件名在这里
      - https://onep.hzchu.top/mount/pic/2023/07/09/64a9ed6c50c22.webp
      - https://onep.hzchu.top/mount/pic/myself/2024/07/669472504bc82.png?fmt=webp
      - https://onep.hzchu.top/mount/pic/myself/2024/07/66947266946f2.png?fmt=webp
      - https://onep.hzchu.top/mount/pic/myself/2024/07/6694727b195a4.png?fmt=webp
      - https://onep.hzchu.top/mount/pic/myself/2024/07/6694728e2531e.png?fmt=webp
  contact:
    content: |  # 这里是加入我们页面的内容，请使用html书写（要不然会很丑）
      <a href="https://jq.qq.com/?_wv=1027&k=erVXhRym" target="_blank"><button>加入QQ群</button></a>
  footer:
    content: |  # 这里是页面底部的内容，请使用html书写
      <script defer src="https://seeyou.hzchu.top/seeyou.js" data-website-id="66c2414e-7322-4d21-9fd6-bc736ac43b74"></script>